# Generated by Django 3.1.6 on 2021-04-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_projectform_suit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectform',
            name='location',
            field=models.CharField(default='Bengaluru', max_length=100),
        ),
    ]
