# Generated by Django 3.1.6 on 2021-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210402_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='unit_desc',
            field=models.CharField(choices=[('0', 'Yet to Review - 0'), ('1', 'Projectmanager Inspected & Snags given to Programhead - 1'), ('2', 'Projectmanager Snags attended & Handed Over - 2'), ('3', 'Customer Intimated for inspection - 3'), ('4', 'Customer Snags Given to Architect - 4'), ('5', 'Customer Snags Attended & Handed over to Supervisor - 5'), ('6', 'Handed over to Customer - 6')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectform',
            name='floor',
            field=models.IntegerField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectform',
            name='tower',
            field=models.CharField(default='', max_length=50),
        ),
    ]
